line-bot:
 channel_access_token: "TvIjkaVoZPa2XpOUCzBEPik2EiOXVIfOh/PAIxjDhJ20NzdTpqa+sSWves2p+F7O4Ydvmy5b9bajuEg19Gg5isXHwf2po+JVF8dbBpUWKX6yz8PClmoJVlO4a1LE7uhq9Evi2Q5cL4l1RxZvyu2LsAdB04t89/1O/w1cDnyilFU="
 channel_secret: "b02678f6aed9dc6bcc2a2447caaa7eb7"
